// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cs_tunering;

#nullable disable

namespace cs_tunering.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240402110913_ChildTournament")]
    partial class ChildTournament
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cs_tunering.ChildTournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentTournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentTournamentId");

                    b.ToTable("ChildTournaments");
                });

            modelBuilder.Entity("cs_tunering.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("cs_tunering.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsParentTournament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("cs_tunering.ChildTournament", b =>
                {
                    b.HasOne("cs_tunering.Tournament", "ParentTournament")
                        .WithMany()
                        .HasForeignKey("ParentTournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTournament");
                });

            modelBuilder.Entity("cs_tunering.Tournament", b =>
                {
                    b.HasOne("cs_tunering.Tournament", null)
                        .WithMany("ChildTournaments")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("cs_tunering.Tournament", b =>
                {
                    b.Navigation("ChildTournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
